# Generated by Django 5.1.7 on 2025-04-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkout',
            name='exercises',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
