# Generated by Django 5.1.7 on 2025-04-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('strength', 'Strength'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('weight_loss', 'Weight Loss'), ('general_fitness', 'General Fitness')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workouts_per_week',
            field=models.IntegerField(),
        ),
    ]
